# Generated by Django 4.0.3 on 2022-04-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
